#include <iostream>
#include <memory>
#include <unordered_map>
#include <vector>

#include <verilated.h>
#include <verilated_vcd_c.h>
#include "Vtop.h" // The header generated by Verilator

vluint64_t main_time = 0; // Global simulation time

/*
1. CPU: Drive load reqs, Virtual Addr, lsq_tags on CPU interface, hold them until the physical tag gets returned from MMU 
2. PTW Requests vs. Cache Requests: The PTW might ask for a 32-bit PTE, while the L1 Cache might concurrently ask for a 512-bit cache line.
The simulated engine should prioritize PTW requests over L2 cache line requests.

*/

class SimulatedEngine {
private:
    Vtop* dut;
    
    int test_modes = 0; // Determine Current Test Type (e.g. TLB Miss-Return, Page Fault, Svadu Handling, etc.)
    std::unordered_map<uint32_t, uint32_t> MEM_DATA; // PTE[satp_in[19:0] + vaddr[31:22]] = L0_PPN;  PTE[L2_PPN + vaddr[21:12]] = DATA_PPN
    
    // Mocked PTE DATA to be returned to PTW (set last hex digit to F for valid, E for invalid to trigger page fault)
    bool ptw_request_pending = false; // Flag that indicates Memory is now busy serving a request
    int ptw_response_counter = 0;
    int ptw_write_req_passthrough = 0;
    uint32_t ptw_mem_addr_passthrough = 0;
    int ptw_mem_write_data_passthrough = 0;

    // L2/Mem block return variables
    uint32_t block_base_addr = 0;
    int block_return_word = 0xAAAA0000;
    bool block_return_request_pending = false;
    int block_return_counter = 0;
    int block_id_passthrough = 0;

    // Constant Latency Modeling
    const int PTW_RESPONSE_LATENCY = 10; // Number of cycles after which PTW response will be ready
    const int L2CACHE_MISS_RETURN_LATENCY = 15;
    const int L2CACHE_HIT_RETURN_LATENCY = 3;

public:
    SimulatedEngine(Vtop* dut_ptr): dut(dut_ptr), ptw_response_counter(0), test_modes(0), ptw_request_pending(false) {}
    
    // Tracking request status
    bool request_done = false;

    // CPU input interface
    void CPU_Drive_Inputs(int vaddr, int load_req_in = 0, int store_req_in = 0, int lsq_tag = 0, int store_data = 0, int store_byte_en = 0, int test_mode = 0) {
        dut->virtual_address_in = vaddr;
        dut->load_req_in = load_req_in;
        dut->store_req_in = store_req_in;
        dut->store_data_in = store_data;
        dut->store_byte_en_in = store_byte_en;

        dut->lsq_tag_in = lsq_tag;
        dut->satp_in = 0x8000ABCD; // set the base address of root page table frame
        dut->flush = 0;
        test_modes = test_mode;
    }


    // CPU output interface
    void CPU_Monitor_Output() {        
        // L1Cache: Waking up awaiting lsq load entries
        if(dut->lsq_wakeup_vector_out){
            if (dut->lsq_wakeup_vector_out != 0) {
                std::cout << "[CPU] LSQ Wakeup Vector asserted: 0x" << std::hex << dut->lsq_wakeup_vector_out << std::dec  << std::endl;
            }
        }

        // TLB: TLB Miss 
        if(dut->Physical_Page_ID_Miss_out && !dut->ptw_busy_out){
            std::cout << "[CPU] TLB Miss detected! Holding request..." << std::endl;
        }

        // TLB: Capturing returned physical tag from TLB
        if(dut->TLB_physical_tag_valid_out && test_modes == 0) {
            std::cout << "[CPU] MMU Translation Successful! TLB Physical Tag is Valid." << std::endl;
            request_done = true;
        }

        // PTW: Indicating PTW is not IDLE
        if(dut->ptw_busy_out && ptw_request_pending && !dut->page_fault_out) {
            std::cout << "PTW is busy walking the page table..." << std::endl;
        }

        // PTW: Unconditional Page Fault Catching
        if(dut->page_fault_out) {
            std::cout << "[CRITICAL] Page Fault detected! PTW fetched an invalid PTE or permission denied!" << std::endl;
        }

        // Main Memory: Capturing PTW write requests for Svadu Handling (D/A Management)
        if(dut->ptw_mem_req_valid_out && dut->ptw_mem_req_type_out && test_modes == 2) {
            std::cout << "Received Updated PTE: 0x" << std::hex << dut->ptw_mem_write_data_out << std::dec << std::endl;
            std::cout << "Test 2 Completed" << std::endl;
        }
    }
    

    void Memory_Response_Handler() {
        
        // PTW Response Handler
        dut->ptw_mem_data_valid_in = 0;
        if(dut->ptw_mem_req_valid_out && !ptw_request_pending) {
            std::cout << "Received PTW Memory Request! Starting countdown for response..." << std::endl;
            ptw_response_counter = PTW_RESPONSE_LATENCY;
            ptw_request_pending = true;
            ptw_write_req_passthrough = dut->ptw_mem_req_type_out; // pass through these signals sicne they're transient
            ptw_mem_addr_passthrough = dut->ptw_mem_addr_out;
            ptw_mem_write_data_passthrough = dut->ptw_mem_write_data_out;
        }

        if(ptw_request_pending) {
            if (ptw_response_counter > 0) {
                ptw_response_counter--;
            }
            else{
                if(ptw_write_req_passthrough){ 
                    // if it is a write request, update the D or A bit.
                    MEM_DATA[ptw_mem_addr_passthrough] = ptw_mem_write_data_passthrough;
                    dut->ptw_mem_data_valid_in = 1; // Remember to assert valid flag to proceed PTW
                    std::cout << "Serving PTW Write Request with PTE = 0x" << std::hex << ptw_mem_write_data_passthrough << std::dec << std::endl;
                }
                else{
                    // if it is a read request, read the PTE
                    if (MEM_DATA.find(ptw_mem_addr_passthrough) != MEM_DATA.end()) {
                        dut->ptw_mem_read_data_in = MEM_DATA[ptw_mem_addr_passthrough];
                    } 
                    else {
                        std::cout << "[WARNING] Unmapped memory read at: 0x" << std::hex << ptw_mem_addr_passthrough << std::dec << std::endl;
                        dut->ptw_mem_read_data_in = 0;
                    }
                    dut->ptw_mem_data_valid_in = 1;
                    std::cout << "Serving PTW Read Request to addr 0x" << std::hex << ptw_mem_addr_passthrough << " with PTE = 0x" << dut->ptw_mem_read_data_in << std::dec << std::endl;
                }
                ptw_request_pending = false;
            }
        }

        // L2/Memory Data Response Handler
        dut->L2_return_block_valid_in = 0;
        if(dut->L2_block_req_out && !dut->L2_return_block_valid_in && !block_return_request_pending) {
            std::cout << "[L2 Memory] Cache Line Request Received for Block ID: 0x" << std::hex << dut->L2_req_block_id_out << std::dec << std::endl;
            block_base_addr = dut->L2_req_block_id_out << 6; // 64 bytes = 2^6 shift to get physical byte address
            
            // Lazy initialization for blocks not hit by Preload()
            if(MEM_DATA.find(block_base_addr) == MEM_DATA.end()) {
                for(int i=0;i<16;i++){
                    MEM_DATA[block_base_addr + (i * 4)] = block_return_word++;
                }
            }
            
            block_return_request_pending = true;
            block_return_counter = L2CACHE_MISS_RETURN_LATENCY;
            block_id_passthrough = dut->L2_req_block_id_out;
        }

        if(block_return_request_pending){
            if(block_return_counter > 0){
                block_return_counter--;
            }
            else{
                std::cout << "[L2 Memory] Returning Cache Line Data to L1 Cache." << std::endl;
                for(int i=0;i<16;i++){
                    dut->L2_return_block_data_in[i] = MEM_DATA[block_base_addr + (i * 4)];
                }
                dut->L2_return_block_valid_in = 1;
                dut->L2_return_block_id_in = block_id_passthrough;
                block_return_request_pending = false;
            }
        }        
    }

    // Pre-load Memory Data
        /* 
            RISC-V Sv32 Page Table Entry (PTE) Format (32 bits total):
            | 31...................10 | 9.......8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0 |
            | Physical Page Num (PPN) | Reserved  | D | A | G | U | X | W | R | V |
            
            V = Valid (1 if page is in memory, 0 if not allocated or on disk)
            R, W, X = Read, Write, Execute permissions
            U = User mode accessible
            G = Global mapping (shared across all processes, ignore ASID of satp and TLB entry)
            A = Accessed (Hardware sets to 1 when read/written)
            D = Dirty (Hardware sets to 1 when written)
        */
    void Preload() {
        // Golden Test Setup for Virtual Address: 0xDEADBEEF
        // satp = 0x8000ABCD -> Base PPN = 0xABCD. Base Phys Addr = 0xABCD0000
        // VPN1 = 0x37A. VPN0 = 0x2DB. Page Offset = 0xEEF.

        // 1. Root Page Table Entry (L1 PTE)
        // Address = 0x0ABCD000 + (0x37A * 4) = 0x0ABCDDE8
        // Map this to an L0 Page Table at physical page 0x1234. (0x1234 << 10) | 0x01 (Valid) = 0x0048D001
        MEM_DATA[0x0ABCDDE8] = 0x0048D001;

        // 2. Leaf Page Table Entry (L0 PTE)
        // Address = (0x1234 << 12) + (0x2DB * 4) = 0x01234B6C
        // Map this to a physical data page at 0x56789. Permissions: D=1, A=1, U=0, X=0, W=1, R=1, V=1 (0xCF)
        MEM_DATA[0x01234B6C] = 0x159E24CF; // (0x56789 << 10) | 0xCF
        
        // 3. Cache Line Data
        // Full Physical Address = 0x56789EEF. Cache Block Base = 0x56789EC0
        for(int i = 0; i < 16; i++) {
            MEM_DATA[0x56789EC0 + (i * 4)] = 0xBEEF0000 + i;
        }
        
        std::cout << "[Preload] Memory initialized with Golden Test page tables and data." << std::endl;
    }
};

void tick_clock(Vtop* dut, VerilatedVcdC* tfp, SimulatedEngine& engine) {
    dut->clk = 0;
    dut->eval();
    tfp->dump(main_time++); // timestamp of current cycle's falling edge (for dumps)
    
    dut->clk = 1;
    dut->eval();
    if(engine.request_done){ // tactically de-assert req in the next cycle.
        engine.CPU_Drive_Inputs(0, 0, 0, 0, 0, 0, 0); // set request
        engine.request_done = false;
    }
    engine.Memory_Response_Handler();
    engine.CPU_Monitor_Output();
    tfp->dump(main_time++); // timestamp of current cycle's rising edge
}



int main(int argc, char** argv) {
    // 1. Setup Engine
    Verilated::commandArgs(argc, argv); 
    Verilated::traceEverOn(true);       

    // 2. Instantiate DUT and Tracer
    Vtop* dut = new Vtop;       
    VerilatedVcdC* tfp = new VerilatedVcdC; 
    SimulatedEngine engine(dut);
    
    dut->trace(tfp, 99);                
    tfp->open("waveform_top.vcd");          

    engine.Preload();

    // 3. The Simulation Loop
    dut->rst_n = 0;
    dut->flush = 0;
    for(int i=0; i<5; i++) tick_clock(dut, tfp, engine); // Hold reset for 5 cycles

    dut->rst_n = 1;
    std::cout << "Reset lifted." << std::endl;

    // DRIVING INPUT INTERFACE
    // Set SATP to point to the root page table frame (for Sv32, the root PTE frame number is the lower bits 22 of SATP
    dut->satp_in = 0x8000ABCD; // The first bit is MODE bit indicating Sv32 and bits [21:20] are hardwired to 0.
    int lsq_tag_in = 3;
    engine.CPU_Drive_Inputs(0xDEADBEEF, 1, 0, lsq_tag_in, 0, 0, 0);
    lsq_tag_in = (lsq_tag_in + 1) % 16;
    for(int i=0; i<100; i++) {
        tick_clock(dut, tfp, engine);
    } 
    // Increased cycle count to allow both PTW (20c) and Cache Fill (15c) to complete

    std::cout << "Simulation Completed" << std::endl;

    dut->final();
    tfp->close();
    delete dut;
    delete tfp;
    return 0;
}